---
- name: Ensure dnf plugins are installed
  ansible.builtin.dnf:
    name: "{{ mailstack_repos_packages }}"
    state: present

- name: Enable CodeReady Builder repository
  community.general.dnf_config_manager:
    name: "{{ mailstack_crb_repo_id }}"
    state: enabled
  when: mailstack_enable_crb | bool

- name: Install EPEL release
  ansible.builtin.dnf:
    name: "{{ mailstack_epel_release_url }}"
    state: present
    disable_gpg_check: true
  when: mailstack_enable_epel | bool

- name: Add upstream Rspamd repository
  ansible.builtin.yum_repository:
    name: rspamd
    description: Rspamd stable repository
    baseurl: "{{ mailstack_rspamd_repo_baseurl }}"
    gpgkey: "{{ mailstack_rspamd_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
  when: mailstack_enable_rspamd_repo | bool
