---
- name: Reload Postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: reloaded
  when: mailstack_start_services | bool

- name: Restart Postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted
  when: mailstack_start_services | bool
